# -*- coding: utf-8 -*-
"""assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaxSCB-R1E8tPOQBmSGmPxrVZnXU_BdV
"""

import pandas as pd

data = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")

y = data['meal']
x = data.drop(['meal','id','DateTime'], axis=1)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report


y = data['meal']
x = data.drop(['meal', 'id', 'DateTime'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier(random_state=42)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Classification Report:\n{report}")

test_data = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv")

x_test_new = test_data.drop(['meal', 'id', 'DateTime'], axis=1)

pred = model.predict(x_test_new)

pred = [int(p) for p in pred]

print(pred[:10])